# Generated by Django 4.2.10 on 2025-09-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_default_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_fullname',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
