# Generated by Django 4.2.10 on 2025-09-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_default_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
