# Generated by Django 4.2.10 on 2025-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_default_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
